# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(40, 20, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(34, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(190, 100, 241, 31))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.pushButton_exibir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exibir.setGeometry(QtCore.QRect(250, 270, 101, 31))
        self.pushButton_exibir.setObjectName("pushButton_exibir")
        self.label_resposta = QtWidgets.QLabel(self.centralwidget)
        self.label_resposta.setGeometry(QtCore.QRect(40, 350, 211, 81))
        self.label_resposta.setWordWrap(True)
        self.label_resposta.setObjectName("label_resposta")
        self.label_idade = QtWidgets.QLabel(self.centralwidget)
        self.label_idade.setGeometry(QtCore.QRect(34, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_idade.setFont(font)
        self.label_idade.setObjectName("label_idade")
        self.lineEdit_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_idade.setGeometry(QtCore.QRect(190, 160, 241, 31))
        self.lineEdit_idade.setObjectName("lineEdit_idade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Programa para exibir o nome digitado"))
        self.label_nome.setText(_translate("MainWindow", "Digite o nome:"))
        self.pushButton_exibir.setText(_translate("MainWindow", "Exibir nome"))
        self.label_resposta.setText(_translate("MainWindow", "."))
        self.label_idade.setText(_translate("MainWindow", "Digite a idade:"))
