# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reprodutormusical.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(70, 220, 93, 28))
        self.pushButton_play.setObjectName("pushButton_play")
        self.pushButton_stop_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop_1.setGeometry(QtCore.QRect(70, 280, 93, 28))
        self.pushButton_stop_1.setObjectName("pushButton_stop_1")
        self.label_imagem_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem_1.setGeometry(QtCore.QRect(30, 50, 161, 141))
        self.label_imagem_1.setText("")
        self.label_imagem_1.setPixmap(QtGui.QPixmap("spotify-icon-free-png.webp"))
        self.label_imagem_1.setScaledContents(True)
        self.label_imagem_1.setObjectName("label_imagem_1")
        self.pushButton_play_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play_2.setGeometry(QtCore.QRect(320, 220, 93, 28))
        self.pushButton_play_2.setObjectName("pushButton_play_2")
        self.pushButton_stop_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop_2.setGeometry(QtCore.QRect(320, 280, 93, 28))
        self.pushButton_stop_2.setObjectName("pushButton_stop_2")
        self.label_imagem_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem_2.setGeometry(QtCore.QRect(290, 50, 161, 141))
        self.label_imagem_2.setText("")
        self.label_imagem_2.setPixmap(QtGui.QPixmap("spotify-icon-free-png.webp"))
        self.label_imagem_2.setScaledContents(True)
        self.label_imagem_2.setObjectName("label_imagem_2")
        self.pushButton_stop_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop_3.setGeometry(QtCore.QRect(580, 280, 93, 28))
        self.pushButton_stop_3.setObjectName("pushButton_stop_3")
        self.pushButton_play_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play_3.setGeometry(QtCore.QRect(580, 220, 93, 28))
        self.pushButton_play_3.setObjectName("pushButton_play_3")
        self.label_imagem_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem_3.setGeometry(QtCore.QRect(540, 50, 161, 141))
        self.label_imagem_3.setText("")
        self.label_imagem_3.setPixmap(QtGui.QPixmap("spotify-icon-free-png.webp"))
        self.label_imagem_3.setScaledContents(True)
        self.label_imagem_3.setObjectName("label_imagem_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 400, 361, 61))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
        self.pushButton_stop_1.setText(_translate("MainWindow", "Parar"))
        self.pushButton_play_2.setText(_translate("MainWindow", "Play"))
        self.pushButton_stop_2.setText(_translate("MainWindow", "Parar"))
        self.pushButton_stop_3.setText(_translate("MainWindow", "Parar"))
        self.pushButton_play_3.setText(_translate("MainWindow", "Play"))
        self.label.setText(_translate("MainWindow", "Escolha uma música"))
