# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soma.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(200, 20, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.lineEdit_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num1.setGeometry(QtCore.QRect(250, 120, 151, 31))
        self.lineEdit_num1.setObjectName("lineEdit_num1")
        self.label_num1 = QtWidgets.QLabel(self.centralwidget)
        self.label_num1.setGeometry(QtCore.QRect(50, 120, 181, 31))
        self.label_num1.setObjectName("label_num1")
        self.label_num2 = QtWidgets.QLabel(self.centralwidget)
        self.label_num2.setGeometry(QtCore.QRect(50, 180, 181, 31))
        self.label_num2.setObjectName("label_num2")
        self.lineEdit_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num2.setGeometry(QtCore.QRect(250, 180, 151, 31))
        self.lineEdit_num2.setObjectName("lineEdit_num2")
        self.pushButton_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calcular.setGeometry(QtCore.QRect(460, 130, 141, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_calcular.setFont(font)
        self.pushButton_calcular.setObjectName("pushButton_calcular")
        self.label_resposta = QtWidgets.QLabel(self.centralwidget)
        self.label_resposta.setGeometry(QtCore.QRect(210, 280, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resposta.setFont(font)
        self.label_resposta.setText("")
        self.label_resposta.setObjectName("label_resposta")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(110, 280, 81, 41))
        self.label_resultado.setObjectName("label_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "SOMAR 2 NÚMEROS"))
        self.label_num1.setText(_translate("MainWindow", "DIGITE O PRIMEIRO NÚMERO:"))
        self.label_num2.setText(_translate("MainWindow", "DIGITE O SEGUNDO NÚMERO:"))
        self.pushButton_calcular.setText(_translate("MainWindow", "CALCULAR"))
        self.label_resultado.setText(_translate("MainWindow", "RESPOSTA:"))
