# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 351, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 51, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 371, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 131, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 131, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 360, 280, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 290, 231, 41))
        self.label_7.setObjectName("label_7")
        self.lineEditcpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditcpf.setGeometry(QtCore.QRect(90, 70, 181, 31))
        self.lineEditcpf.setObjectName("lineEditcpf")
        self.lineEditpt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditpt.setGeometry(QtCore.QRect(170, 180, 181, 31))
        self.lineEditpt.setObjectName("lineEditpt")
        self.lineEditmat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditmat.setGeometry(QtCore.QRect(180, 230, 181, 31))
        self.lineEditmat.setObjectName("lineEditmat")
        self.lineEditgeral = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditgeral.setGeometry(QtCore.QRect(280, 290, 181, 31))
        self.lineEditgeral.setObjectName("lineEditgeral")
        self.lineEditespecifico = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditespecifico.setGeometry(QtCore.QRect(330, 360, 181, 31))
        self.lineEditespecifico.setObjectName("lineEditespecifico")
        self.pushButtonCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancelar.setGeometry(QtCore.QRect(220, 460, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonCancelar.setFont(font)
        self.pushButtonCancelar.setObjectName("pushButtonCancelar")
        self.pushButtonSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSalvar.setGeometry(QtCore.QRect(480, 460, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonSalvar.setFont(font)
        self.pushButtonSalvar.setObjectName("pushButtonSalvar")
        self.labelMedia = QtWidgets.QLabel(self.centralwidget)
        self.labelMedia.setGeometry(QtCore.QRect(600, 260, 111, 61))
        self.labelMedia.setText("")
        self.labelMedia.setObjectName("labelMedia")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastro das notas dos candidatos"))
        self.label_2.setText(_translate("MainWindow", "CPF:"))
        self.label_3.setText(_translate("MainWindow", "Digite a quantidade de acertos em:"))
        self.label_4.setText(_translate("MainWindow", "Português:"))
        self.label_5.setText(_translate("MainWindow", "Matemática:"))
        self.label_6.setText(_translate("MainWindow", "Conhecimentos Específicos:"))
        self.label_7.setText(_translate("MainWindow", "Conhecimentos Gerais:"))
        self.pushButtonCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.pushButtonSalvar.setText(_translate("MainWindow", "Salvar Notas"))
