# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sonic.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_sonic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sonic.setGeometry(QtCore.QRect(30, 180, 110, 28))
        self.pushButton_sonic.setStyleSheet("QPushButton{\n"
"background-color: #0000ff;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"}")
        self.pushButton_sonic.setObjectName("pushButton_sonic")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(240, 10, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(30)
        font.setItalic(False)
        self.title.setFont(font)
        self.title.setStyleSheet("color: #ffc517;")
        self.title.setObjectName("title")
        self.pushButton_knuckles = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_knuckles.setGeometry(QtCore.QRect(650, 180, 110, 28))
        self.pushButton_knuckles.setStyleSheet("QPushButton{\n"
"background-color: #aa0000;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"}")
        self.pushButton_knuckles.setObjectName("pushButton_knuckles")
        self.pushButton_tails = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tails.setGeometry(QtCore.QRect(30, 270, 110, 28))
        self.pushButton_tails.setStyleSheet("QPushButton{\n"
"background-color: #ffcc11;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"}")
        self.pushButton_tails.setObjectName("pushButton_tails")
        self.pushButton_amy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_amy.setGeometry(QtCore.QRect(30, 360, 110, 28))
        self.pushButton_amy.setStyleSheet("QPushButton{\n"
"background-color: #ff00ff;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"}")
        self.pushButton_amy.setObjectName("pushButton_amy")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(340, 470, 121, 31))
        self.pushButton_play.setStyleSheet("QPushButton{\n"
"background-color: #00aaff;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_play.setObjectName("pushButton_play")
        self.pushButton_shadow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shadow.setGeometry(QtCore.QRect(650, 290, 110, 28))
        self.pushButton_shadow.setStyleSheet("QPushButton{\n"
"background-color: #000000;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"}")
        self.pushButton_shadow.setObjectName("pushButton_shadow")
        self.pushButton_dr_eggman = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dr_eggman.setGeometry(QtCore.QRect(650, 380, 110, 28))
        self.pushButton_dr_eggman.setStyleSheet("QPushButton{\n"
"background-color: #4CAF50;\n"
"color: white;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"}")
        self.pushButton_dr_eggman.setObjectName("pushButton_dr_eggman")
        self.img_fundo = QtWidgets.QLabel(self.centralwidget)
        self.img_fundo.setGeometry(QtCore.QRect(0, 0, 781, 551))
        self.img_fundo.setText("")
        self.img_fundo.setPixmap(QtGui.QPixmap("fundo.png"))
        self.img_fundo.setScaledContents(True)
        self.img_fundo.setObjectName("img_fundo")
        self.label_PersonagemSelecionado = QtWidgets.QLabel(self.centralwidget)
        self.label_PersonagemSelecionado.setGeometry(QtCore.QRect(260, 170, 261, 281))
        self.label_PersonagemSelecionado.setText("")
        self.label_PersonagemSelecionado.setObjectName("label_PersonagemSelecionado")
        self.img_fundo.raise_()
        self.pushButton_sonic.raise_()
        self.title.raise_()
        self.pushButton_knuckles.raise_()
        self.pushButton_tails.raise_()
        self.pushButton_amy.raise_()
        self.pushButton_play.raise_()
        self.pushButton_shadow.raise_()
        self.pushButton_dr_eggman.raise_()
        self.label_PersonagemSelecionado.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_sonic.setText(_translate("MainWindow", "SONIC"))
        self.title.setText(_translate("MainWindow", "Escolha seu Personagem:"))
        self.pushButton_knuckles.setText(_translate("MainWindow", "KNUCKLES"))
        self.pushButton_tails.setText(_translate("MainWindow", "TAILS"))
        self.pushButton_amy.setText(_translate("MainWindow", "AMY"))
        self.pushButton_play.setText(_translate("MainWindow", "PLAY"))
        self.pushButton_shadow.setText(_translate("MainWindow", "SHADOW"))
        self.pushButton_dr_eggman.setText(_translate("MainWindow", "DR. EGGMAN"))
