# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ati6.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelResposta = QtWidgets.QLabel(self.centralwidget)
        self.labelResposta.setGeometry(QtCore.QRect(200, 240, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelResposta.setFont(font)
        self.labelResposta.setText("")
        self.labelResposta.setObjectName("labelResposta")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(260, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_num = QtWidgets.QLabel(self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(100, 140, 151, 41))
        self.label_num.setObjectName("label_num")
        self.lineEditNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum.setGeometry(QtCore.QRect(270, 140, 141, 31))
        self.lineEditNum.setText("")
        self.lineEditNum.setObjectName("lineEditNum")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(450, 140, 93, 28))
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Primo"))
        self.label_num.setText(_translate("MainWindow", "DIGITE 1 NÚMERO:"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Mandar"))
